apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cdpipelines.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: CDPipeline
    listKind: CDPipelineList
    plural: cdpipelines
    singular: cdpipeline
    shortNames:
      - cdp
  scope: Namespaced
  x-kubernetes-preserve-unknown-fields: true
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
            status:
              type: object
