apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: stages.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: Stage
    listKind: StageList
    plural: stages
    singular: stage
    shortNames:
      - stg
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
            status:
              type: object
