apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}-edp
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          command:
            - {{ .Values.name }}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ .Values.name }}
            - name: PLATFORM_TYPE
              value: "{{ .Values.platform }}"
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_PORT
              value: "{{ .Values.database.port }}"
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-admin-console
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-admin-console
                  key: password
            - name: DB_SSL_MODE
              value: "disable"