apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: cdpipelines.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: CDPipeline
    listKind: CDPipelineList
    plural: cdpipelines
    singular: cdpipeline
    shortNames:
      - cdp
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
