apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.edp.name }}-edp-deploy
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  activeDeadlineSeconds: 3600
  template:
    metadata:
      name: edp-deploy
    spec:
      securityContext:
        runAsUser: 1000
      restartPolicy: Never
      serviceAccount: edp
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: edp-install-wizard-db-1
      containers:
        - image: {{ .Values.edp.version }}
          imagePullPolicy: Always
          name: edp-deploy
          env:
            - name: DEV_DEPLOY
              value: "{{ .Values.edp.devDeploy }}"
            - name: STAGES_VERSION
              value: "{{ .Values.jenkins.stagesVersion }}"
            - name: PIPELINES_VERSION
              value: "{{ .Values.jenkins.pipelinesVersion }}"
            - name: PLATFORM_TYPE
              value: "{{ .Values.edp.platform }}"
            - name: DEPLOY_PROJECT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - "ansible-playbook"
            - "-v"
            - "-i"
            - "localhost,"
            - "-e edp_name={{ .Values.edp.name }}"
            - "-e additional_tools_template_name={{ .Values.edp.additionalToolsTemplate }}"
            {{ if eq .Values.edp.platform "openshift"  }}
            - "-e console_tool=oc"
            {{ else }}
            - "-e console_tool=kubectl"
            {{ end }}
            - "-e ansible_connection=local"
            - "-e shared_database=edp-install-wizard-db"
            - "-e super_admin_users={{ .Values.edp.superAdmins }}"
            - "-e admin_users={{ .Values.edp.admins }}"
            - "-e view_users={{ .Values.edp.viewers }}"
            - "-e edp_version={{ .Values.edp.version }}"
            - "-e dns_wildcard={{ .Values.edp.dnsWildCard }}"
            - "-e storage_class_name={{ .Values.edp.storageClass }}"
            - "-e jenkins_volume_capacity={{ .Values.jenkins.volumeCapacity }}"
            - "-e jenkins_image_version={{ .Values.jenkins.version }}"
            - "-e jenkins_init_image={{ .Values.jenkins.initImage }}"
            - "-e admin_console_version={{ .Values.adminConsole.version }}"
            - "-e perf_integration_enabled={{ .Values.perf.enabled }}"
            - "-e perf_node_id={{ .Values.perf.nodeId }}"
            - "-e perf_url={{ .Values.perf.url }}"
            - "-e keycloak_namespace={{ .Values.edp.keycloakNamespace }}"
            - "-e keycloak_url={{ .Values.edp.keycloakUrl }}"
            - "ansible-playbooks/install.yml"
