{{- if eq .Values.edp.platform "kubernetes"  -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edp-{{ .Values.edp.name }}-admin
  namespace: {{ .Values.edp.name }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: edp
{{- end -}}
