{{- if eq .Values.edp.platform "openshift"  -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: edp-{{ .Values.edp.name }}-admin
  namespace: {{ .Values.edp.name }}
roleRef:
  name: admin
subjects:
- kind: User
  name: admin
- kind: User
  name: system:serviceaccount:{{ .Values.edp.name }}:edp
userNames:
- admin
- system:serviceaccount:{{ .Values.edp.name }}:edp
groupNames: []
{{- end -}}
