apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nexuses.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: Nexus
    listKind: NexusList
    plural: nexuses
    singular: nexus
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/scripts-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/scripts-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              properties:
                users:
                  items:
                    type: object
                  type: array
                volumes:
                  items:
                    properties:
                      capacity:
                        type: string
                      name:
                        type: string
                    required:
                      - name
                      - capacity
                    type: object
                  type: array
                basePath:
                  type: string
                keycloakSpec:
                  properties:
                    enabled:
                      type: boolean
                  required:
                    - enabled
                  type: object
                version:
                  type: string
                image:
                  type: string
              required:
                - image
                - version
                - keycloakSpec
                - volumes
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
