apiVersion: v2.edp.epam.com/v1alpha1
kind: Jenkins
metadata:
  name: example-jenkins
spec:
  version: "2.2.0"
  image: "epamedp/edp-jenkins"
  initImage: "busybox"
  volumes:
    - name: "data"
      storageClass: "gp2"
      capacity: "1Gi"
  sharedLibraries:
    - name: "edp-library-stages"
      id: "Stages"
      repository: "https://github.com/epmd-edp/edp-library-stages.git"
      version: "2.1.0"
    - name: "edp-library-pipelines"
      id: "Pipelines"
      repository: "https://github.com/epmd-edp/edp-library-pipelines.git"
      version: "2.1.0"
  keycloakSpec:
    enabled: false
  edpSpec:
    dnsWildcard: "delivery.aws.main.edp.projects.epam.com"