{{- if eq .Values.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-edp-{{ .Values.namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: edp-{{ .Values.name }}-role-{{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-edp
    namespace: {{ .Values.namespace }}
{{- end -}}