name: codebase-operator
namespace: ""
platform: "openshift"
database:
  required: false
  host: edp-install-wizard-db
  name: edp-install-wizard-db
  port: 5432
image:
  name: epamedp/codebase-operator
  version: v2.3.0