apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sonars.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: Sonar
    listKind: SonarList
    plural: sonars
    singular: sonar
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            initImage:
              type: string
            dbImage:
              type: string
            edpSpec:
              properties:
                dnsWildcard:
                  type: string
              required:
                - dnsWildcard
            version:
              type: string
            basePath:
              type: string
            volumes:
              items:
                properties:
                  capacity:
                    type: string
                  name:
                    type: string
                required:
                  - name
                  - capacity
                type: object
              type: array
          required:
            - image
            - initImage
            - dbImage
            - version
            - edpSpec
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
