apiVersion: v2.edp.epam.com/v1alpha1
kind: Sonar
metadata:
  name: example-sonar
spec:
  image: "sonarqube"
  initImage: "busybox"
  dbImage: "postgres:9.6"
  version: "7.9-community"
  basePath: ""
  edpSpec:
    dnsWildcard: core-platform.aws.main.edp.projects.epam.com
  volumes:
    - name: "data"
      storage_class: "gp2"
      capacity: "1Gi"
    - name: "db"
      storage_class: "gp2"
      capacity: "1Gi"