apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codebaseimagestreams.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: CodebaseImageStream
    listKind: CodebaseImageStreamList
    plural: codebaseimagestreams
    singular: codebaseimagestream
    shortNames:
      - cbis
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
