apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: codebases.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: Codebase
    listKind: CodebaseList
    plural: codebases
    singular: codebase
    shortNames:
      - cdbs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            lang:
              type: string
            type:
              type: string
            description:
              anyOf:
                - type: null
                - type: string
            framework:
              anyOf:
                - type: null
                - type: string
            testReportFramework:
              type: string
            buildTool:
              type: string
            strategy:
              type: string
            versioning:
              properties:
                type:
                  type: string
                startFrom:
                  anyOf:
                    - type: null
                    - type: string
              required:
                - type
            git:
              properties:
                url:
                  type: string
              required:
                - url
            route:
              properties:
                site:
                  type: string
                path:
                  type: string
          required:
            - lang
            - type
            - buildTool
            - strategy
            - versioning
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
