apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: codebasebranches.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: CodebaseBranch
    listKind: CodebaseBranchList
    plural: codebasebranches
    singular: codebasebranch
    shortNames:
      - cb
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              properties:
                codebaseName:
                  type: string
                branchName:
                  type: string
                fromCommit:
                  type: string
                version:
                  type: string
                build:
                  type: string
                release:
                  type: boolean
                data:
                  type: string
                  properties:
                    key:
                      type: string
                    name:
                      type: string
              required:
                - codebaseName
                - branchName
                - fromCommit
                - release
              type: object
            status:
              type: object
